### ISSUE TITLE
Ability to set MTU for the VF

### ISSUE THREAD

**Issue by svallala** [intel/sriov-cni#123]
## What would you like to be added?
Ability to set the MTU for the VF by sending the configuration

## What is the use case for this feature / enhancement?
I have a PF configured with 9000, but the VF attached inside the Pod shows up with default 1500. I am trying to solve this using the tuning plugin, but it is better to handle this by the CNI plugin instead of a need for an additional plugin to configure this.

if CNI handles this, there is an opportunity to reset the MTU for VF back to the original MTU as part of the reset VF function. I don't see MTU in the VF parameters is there a reason?

Thanks

**Comment by killianmuldoon** [comment]
The SR-IOV CNI deals mainly with setting up (and taking down) VFs. I don't think MTU has a special meaning in a VF context and I'm not sure this is the right project for configuring generic fields of the kernel networking driver - but I'm happy for others to jump in and we can see if there's a good argument for this feature.

**Comment by moshe010** [comment]
MTU is just in the context of the VF netdevice like all other interfaces. I didn't get why tuning plugin is not a good solution here?

**Comment by svallala** [comment]
I was hoping it can be handled by the CNI. If I use the tuning plugin to set the MTU, there is no way to reset the value back after the VF is released. Plugin today allows setting the MAC address, why is MTU not part of that parameter list? There are some plugins that have MTU as one of the parameters.

I am okay if this parameter is not part of the list, but then if I have my PF configured with MTU 9000, I would expect that the VFs created should be set to 9000. By default, they are getting created with an MTU of 1500.

**Comment by moshe010** [comment]
I didn't say I am against it. The mac address is not a good example because for VF you have the administrative mac (VF mac) and the effective mac (netdevice mac which is what tuning can config). And we didn't want to configure them in both places. MTU is not really VF configuration is the netdevice configuration.  Anyway I am fine to add this as configuration for the VF to resolve the issue to restore the value   (if others will approve)

**Comment by svallala** [comment]
@moshe010 I submitted changes to support setting MTU. If folks approve and review these can be merged.
https://github.com/intel/sriov-cni/pull/124

**Comment by krishnajs** [comment]
@svallala regarding your point that if PF MTU is set to 9k then all VFs should be set to 9k might not be the right case. Each application that uses VF might have different MTU requirements. Regarding the point you mentioned about MAC address - it is being set I guess because VFs, when created, will not have the MAC address set and we can not set it from within the application POD. Default MTU of 1500 is set on all interfaces.

**Comment by svallala** [comment]
@krishnajs, yes you are absolutely right, each VF could be set to a different MTU based on the application needs. There is no way to set the MTU today for a VF unless you provide additional privileges for the Pod. The changes I submitted, is an attempt to provide that flexibility.

**Comment by krishnajs** [comment]
@svallala MTU can be only on the interface where the kernel driver is being used but not when DPDK is being used. Also to your point - " If I use the tuning plugin to set the MTU, there is no way to reset the value back after the VF is released. "  Why are we worried about resetting since we can set a new value when we deploy the pod again?

**Comment by killianmuldoon** [comment]
This seems to be an issue for kernel interfaces only, and there's no clear way to communicate this as part of the config. The direction right now is still to set the MTU with the tuning cni using a chained plugin in the network attachment definition. 

@svallala it would be great if you could provide an example config using this model and we can add a doc that explains how to implement this use case and the caveats with it.
