### ISSUE TITLE
Should we deprecate support of allocating VF using master PF?

### ISSUE THREAD

**Issue by ahalim-intel** [intel/sriov-cni#69]
@rkamudhan 
@zshi-redhat 

With introduction of [sriov-device-plugin](https://github.com/intel/sriov-network-device-plugin) the sriov-cni no longer needs to find and allocate unused VF using a `master`(SRIOV PF ) interface. Using the master interface to determine and allocate a free VF to a container has other unwanted consequences too. **It's not concurrency safe**. For proper resource accounting and allocation in K8s the device plugin should be used. Device plugin also takes care of device files permission issues should a VF requires any device files in the container(e.g. vfio, rdma etc.). With that in mind, attaching dpdk driver in CNI is no longer needed. Currently, deprecating DPDKConf is in progress. Should we also remove the `master` field from the json conf and only allow user to specify the VF's pci address as `deviceID`(ideally this should be coming thourgh sriov-device-plugin).

What is your opinion on this?

**Comment by zshi-redhat** [comment]
+1 on the removal.
I had the impression that we support ``master`` PF config due to legacy or backward compatibility, besides that, it's reasonably for me to deprecate it as more advanced features can not be added or used with the master PF mode, like vfio, rdma mentioned above or the coming NUMA awareness, Resource Class API, Device Monitoring etc, it will make master PF mode useless without further performance/functional enhancement. 
Also looking at the github issues, I didn't see anything specific to master PF mode which I guess most of people are actually not using that mode and our development efforts are more focused on DP + CNI instead of improving the master PF mode. 
Meanwhile, with the vfio/uio device supported in Device Plugin, I think we have basically covered most(if not all) of the functionalities that legacy SR-IOV CNI supports, so it's safe to remove it.

**Comment by ahalim-intel** [comment]
@zshi-redhat Thanks for your feedback. 
Also, there's still some issue remains with dpdk mode support even with fix #64 applied. We didn't address how user is going to indicate that allocated device is for dpdk mode(I guess only option is user l needs to provide a "dpdk" conf. In this case plugin should throw in error because it can't get a netdevice for the VF).

Here is a [sneak peek](https://github.com/ahalim-intel/sriov-cni/tree/dev/deprecate_dpdkconf_rebased) of planned changes: This is a WIP.

Overall flow of VF setup and tear-down is simplified and easier to understand IMO. Applied more refactoring to make code testable. I've rebased #61(which is has issues running tests on travis) with current master and fixed all build and travis-ci issues.

I still need to investigate on support of shared VF with the new approach.

**Comment by zshi-redhat** [comment]
> @zshi-redhat Thanks for your feedback.
> Also, there still some issue remains with dpdk mode support even with fix #64 applied. We didn't address how user is going to indicate that allocated device is for dpdk mode(I guess only option is user l needs to provide a "dpdk" conf. In this case plugin should throw in error because it can't get a netdevice for the VF).

when the "dpdk" conf is provided, shall the plugin do nothing and return success?
I think with the ''dpdk'' conf, plugin doesn't need to detect the netlink state of a  given device, it can rely on the conf to switch between a netdevice config path and a vfio/uio config path.

**Comment by killianmuldoon** [comment]
@ahalim-intel @zshi-redhat This issue was closed wit #71   right?

**Comment by ahalim-intel** [comment]
yes, we can close this
